server:
  port: 8088
  servlet:
    context-path: /prodProject

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/echat
    username: root
    password:
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,log4j2
      stat-view-servlet:
        allow: 127.0.0.1
        enabled: true
        reset-enable: false
        login-username: admin
        login-password: admin

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mavenproject.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true

#debug: true